name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  CONTAINER_NAME: grimoire-api

jobs:
  run:
    name: Pull Docker Image and Run Container
    runs-on: ubuntu-latest
    steps:
      - run: echo "REPOSITORY=${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV
      - run: echo "DOCKER_IMAGE=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest" >> $GITHUB_ENV

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo docker login --username ${{ github.repository_owner }} --password ${{ secrets.REGISTRY_TOKEN }} ${{ env.REGISTRY }}
            sudo docker pull ${{ env.DOCKER_IMAGE }}
            sudo docker stop ${{ env.CONTAINER_NAME }} || true
            sudo docker rm ${{ env.CONTAINER_NAME }} || true
            sudo docker run -d -p 80:8080 --name  ${{ env.CONTAINER_NAME }} ${{ env.DOCKER_IMAGE }}
