name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  CONTAINER_NAME: grimoire-api

jobs:
  run:
    name: Pull Docker Image and Run Container
    runs-on: self-hosted
    steps:
      - run: echo "REPOSITORY=${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV
      - run: echo "DOCKER_IMAGE=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: sudo docker login --username ${{ github.repository_owner }} --password ${{ secrets.REGISTRY_TOKEN }} ${{ env.REGISTRY }}

      - name: Pull Docker Image
        run: sudo docker pull ${{ env.DOCKER_IMAGE }}

      - name: Delete Old Docker Container
        run: |
          sudo docker stop ${{ env.CONTAINER_NAME }} || true
          sudo docker rm ${{ env.CONTAINER_NAME }} || true

      - name: Run Docker Container
        run: sudo docker run -d -p 80:8080 --name  ${{ env.CONTAINER_NAME }} ${{ env.DOCKER_IMAGE }}
