name: Continuous Integration

on:
  push:
    branches: main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build an Image and Push to Github Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          echo "REPOSITORY=${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest" >> $GITHUB_ENV

      - name: Login to Github Container Registry
        run: docker login --username ${{ github.repository_owner }} --password ${{ secrets.REGISTRY_TOKEN }} ${{ env.REGISTRY }}

      - name: Build an Image
        run: docker build . --tag ${{ env.DOCKER_IMAGE }}

      - name: Push the Image to Github Container Registry
        run: docker push ${{ env.DOCKER_IMAGE }}
